// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientificTrendTracker.Data;

#nullable disable

namespace ScientificTrendTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624123722_AddLogsPageTables")]
    partial class AddLogsPageTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.AdminActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LogId");

                    b.ToTable("AdminActivityLogs", (string)null);
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ApiDataSource", b =>
                {
                    b.Property<int>("DataSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DataSourceId"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SyncFrequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DataSourceId");

                    b.ToTable("ApiDataSources", (string)null);
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ApiSyncLog", b =>
                {
                    b.Property<int>("SyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SyncLogId"));

                    b.Property<int>("DataSourceId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("RecordsImported")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("SyncFinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SyncStartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SyncLogId");

                    b.HasIndex("DataSourceId");

                    b.ToTable("ApiSyncLogs", (string)null);
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Affiliation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OpenAlexId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookmarkId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeywordId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookmarkId");

                    b.HasIndex("KeywordId");

                    b.HasIndex("PaperId");

                    b.ToTable("Bookmarks", (string)null);
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Journal", b =>
                {
                    b.Property<string>("JournalId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("HIndex")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImpactFactor")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("IndexingDatabase")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IssnElectronic")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IssnPrint")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("JournalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OpenAlexId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("QuartileRank")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("RankingYear")
                        .HasColumnType("int");

                    b.HasKey("JournalId");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Keyword", b =>
                {
                    b.Property<string>("KeywordId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeywordName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("KeywordId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperAuthor", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorOrder")
                        .HasColumnType("int");

                    b.HasKey("PaperId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("PaperAuthors");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperCitation", b =>
                {
                    b.Property<string>("CitingPaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CitedPaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CitingPaperId", "CitedPaperId");

                    b.HasIndex("CitedPaperId");

                    b.ToTable("PaperCitations");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperKeyword", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KeywordId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaperId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("PaperKeywords");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ResearchPaper", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CitationCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAiProcessed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JournalId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OpenAlexId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PaperId");

                    b.HasIndex("JournalId");

                    b.ToTable("ResearchPapers");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.SearchHistory", b =>
                {
                    b.Property<int>("SearchHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SearchHistoryId"));

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SearchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SearchHistoryId");

                    b.ToTable("SearchHistories", (string)null);
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PlanId");

                    b.ToTable("SubscriptionPlans", (string)null);
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.UserSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PlanId");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ApiSyncLog", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.ApiDataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Bookmark", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId");

                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId");

                    b.Navigation("Keyword");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperAuthor", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.Author", "Author")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "Paper")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperCitation", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "CitedPaper")
                        .WithMany("CitationsReceived")
                        .HasForeignKey("CitedPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "CitingPaper")
                        .WithMany("CitationsMade")
                        .HasForeignKey("CitingPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CitedPaper");

                    b.Navigation("CitingPaper");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperKeyword", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.Keyword", "Keyword")
                        .WithMany("PaperKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "Paper")
                        .WithMany("PaperKeywords")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ResearchPaper", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.Journal", "Journal")
                        .WithMany("ResearchPapers")
                        .HasForeignKey("JournalId");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.UserSubscription", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Author", b =>
                {
                    b.Navigation("PaperAuthors");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Journal", b =>
                {
                    b.Navigation("ResearchPapers");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Keyword", b =>
                {
                    b.Navigation("PaperKeywords");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ResearchPaper", b =>
                {
                    b.Navigation("CitationsMade");

                    b.Navigation("CitationsReceived");

                    b.Navigation("PaperAuthors");

                    b.Navigation("PaperKeywords");
                });
#pragma warning restore 612, 618
        }
    }
}
