// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientificTrendTracker.Data;

#nullable disable

namespace ScientificTrendTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622134015_AddPaperTopic")]
    partial class AddPaperTopic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Affiliation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OpenAlexId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Journal", b =>
                {
                    b.Property<string>("JournalId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("HIndex")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImpactFactor")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("IndexingDatabase")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IssnElectronic")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IssnPrint")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("JournalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OpenAlexId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("QuartileRank")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("RankingYear")
                        .HasColumnType("int");

                    b.HasKey("JournalId");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Keyword", b =>
                {
                    b.Property<string>("KeywordId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KeywordName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("KeywordId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperAuthor", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorOrder")
                        .HasColumnType("int");

                    b.HasKey("PaperId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("PaperAuthors");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperCitation", b =>
                {
                    b.Property<string>("CitingPaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CitedPaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CitingPaperId", "CitedPaperId");

                    b.HasIndex("CitedPaperId");

                    b.ToTable("PaperCitations");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperKeyword", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KeywordId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaperId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("PaperKeywords");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ResearchPaper", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CitationCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAiProcessed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JournalId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OpenAlexId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Topic")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PaperId");

                    b.HasIndex("JournalId");

                    b.ToTable("ResearchPapers");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperAuthor", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.Author", "Author")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "Paper")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperCitation", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "CitedPaper")
                        .WithMany("CitationsReceived")
                        .HasForeignKey("CitedPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "CitingPaper")
                        .WithMany("CitationsMade")
                        .HasForeignKey("CitingPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CitedPaper");

                    b.Navigation("CitingPaper");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.PaperKeyword", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.Keyword", "Keyword")
                        .WithMany("PaperKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificTrendTracker.Models.Entities.ResearchPaper", "Paper")
                        .WithMany("PaperKeywords")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ResearchPaper", b =>
                {
                    b.HasOne("ScientificTrendTracker.Models.Entities.Journal", "Journal")
                        .WithMany("ResearchPapers")
                        .HasForeignKey("JournalId");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Author", b =>
                {
                    b.Navigation("PaperAuthors");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Journal", b =>
                {
                    b.Navigation("ResearchPapers");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.Keyword", b =>
                {
                    b.Navigation("PaperKeywords");
                });

            modelBuilder.Entity("ScientificTrendTracker.Models.Entities.ResearchPaper", b =>
                {
                    b.Navigation("CitationsMade");

                    b.Navigation("CitationsReceived");

                    b.Navigation("PaperAuthors");

                    b.Navigation("PaperKeywords");
                });
#pragma warning restore 612, 618
        }
    }
}
